import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // The Claude Design handoff bundle — reference prototypes, not app source.
    "project/**",
    // Vendored agent skills — third-party code, not ours to lint or fix.
    ".claude/skills/**",
    ".agents/**",
    // Payload writes these; `payload migrate:create` regenerates them verbatim,
    // so any fix here is undone by the next migration.
    "src/payload/migrations/**",
    // Generated by `payload generate:importmap`, same reasoning.
    "src/app/(payload)/admin/importMap.js",
    "src/payload-types.ts",
  ]),
]);

export default eslintConfig;
