/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    media: Media;
    categories: Category;
    news: News;
    webinars: Webinar;
    insights: Insight;
    glossary: Glossary;
    'team-members': TeamMember;
    faqs: Faq;
    'media-coverage': MediaCoverage;
    jobs: Job;
    'job-applications': JobApplication;
    'applicant-documents': ApplicantDocument;
    'audit-log': AuditLog;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    jobs: {
      applications: 'job-applications';
    };
  };
  collectionsSelect: {
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    news: NewsSelect<false> | NewsSelect<true>;
    webinars: WebinarsSelect<false> | WebinarsSelect<true>;
    insights: InsightsSelect<false> | InsightsSelect<true>;
    glossary: GlossarySelect<false> | GlossarySelect<true>;
    'team-members': TeamMembersSelect<false> | TeamMembersSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    'media-coverage': MediaCoverageSelect<false> | MediaCoverageSelect<true>;
    jobs: JobsSelect<false> | JobsSelect<true>;
    'job-applications': JobApplicationsSelect<false> | JobApplicationsSelect<true>;
    'applicant-documents': ApplicantDocumentsSelect<false> | ApplicantDocumentsSelect<true>;
    'audit-log': AuditLogSelect<false> | AuditLogSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'upcoming-events': UpcomingEvent;
  };
  globalsSelect: {
    'upcoming-events': UpcomingEventsSelect<false> | UpcomingEventsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Images and documents used across the site. Images are converted to WebP and resized automatically.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * What the image shows, for screen readers and for when it fails to load. Describe it; do not start with "image of". Leave it as a single space for purely decorative artwork.
   */
  alt: string;
  /**
   * Optional photographer or source, where one has to be shown.
   */
  credit?: string | null;
  /**
   * What the CMS did to this file when it was uploaded. Set automatically.
   */
  optimization?: {
    strategy?: string | null;
    originalBytes?: number | null;
    optimizedBytes?: number | null;
    note?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    content?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * The labels that group content across the site. Each one belongs to a single section.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  /**
   * The label as it appears on the site, e.g. Announcement, Case study.
   */
  name: string;
  /**
   * Which section this category belongs to. It will only be offered to content in that section.
   */
  taxonomy: 'news' | 'webinar' | 'insight' | 'faq' | 'media-coverage' | 'glossary';
  /**
   * Leave blank to generate it from the title.
   */
  slug?: string | null;
  /**
   * Lower numbers appear first in filters and tabs. Ties fall back to alphabetical order.
   */
  order: number;
  /**
   * Optional. Not currently shown on the site; useful context for editors.
   */
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Announcements, launches and press releases. Stories get their own page; notices are a dated line in the archive.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news".
 */
export interface News {
  id: number;
  /**
   * Which shape this entry takes in the archive.
   */
  format: 'story' | 'notice';
  /**
   * The card headline. Keep it short — around eight words. A press-release headline set at card size wraps to five lines and buries everything under it.
   */
  title: string;
  /**
   * Optional. The full formal headline, used on the story page where there is room. Falls back to the title.
   */
  headline?: string | null;
  /**
   * The page's address: /resources/news/…  Leave blank to generate it from the title.
   */
  slug?: string | null;
  /**
   * The standfirst: one or two sentences under the headline, and the summary shown on cards and in search results.
   */
  excerpt: string;
  /**
   * Managed under Categories. Add one there if the right label does not exist yet.
   */
  category: number | Category;
  /**
   * The date shown on the page and used for ordering.
   */
  publishedAt: string;
  /**
   * Shown on the card and at the top of the story. 16:9 crops best.
   */
  image?: (number | null) | Media;
  /**
   * The article itself. Left empty, the page shows the headline, standfirst and artwork alone — which is the right answer for a story whose full text lives elsewhere.
   */
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Additional images shown after the article.
   */
  gallery?:
    | {
        image: number | Media;
        /**
         * Optional. Printed under the image. Leave blank where the picture speaks for itself.
         */
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Press releases, statements or data files offered alongside the story.
   */
  attachments?:
    | {
        file: number | Media;
        /**
         * The link text, e.g. “Annual report 2026”. Not the file name.
         */
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional. An author or issuing office, e.g. “Bhutan NDI Communications”. Left blank, no byline is shown.
   */
  byline?: string | null;
  /**
   * Optional. Where the notice links to. Leave blank and the notice gets its own page on this site instead.
   */
  externalUrl?: string | null;
  /**
   * Optional. Shown as a link at the foot of a story whose canonical version was published elsewhere.
   */
  source?: {
    /**
     * The full address, including https://.
     */
    url?: string | null;
    /**
     * The link text.
     */
    label?: string | null;
    kind?: ('article' | 'video') | null;
  };
  /**
   * Lead the newsroom with this story. With none set, the newest story leads; with several, the newest of them does.
   */
  featured?: boolean | null;
  /**
   * Optional. 1 appears first in the “Popular” rail. Leave blank to keep a story out of it.
   */
  popularRank?: number | null;
  /**
   * Optional. Anything left blank falls back to the page's own content, which is usually the right answer.
   */
  meta?: {
    /**
     * Shown in search results and the browser tab. Around 60 characters. Defaults to the title.
     */
    title?: string | null;
    /**
     * The snippet under the search result. Around 155 characters. Defaults to the standfirst.
     */
    description?: string | null;
    /**
     * Used when the page is shared on social media. 1200×630 works everywhere. Defaults to the featured image.
     */
    image?: (number | null) | Media;
    /**
     * Keeps the page out of Google. The page stays reachable by anyone with the link.
     */
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Walkthroughs, integration sessions and recorded talks. Set the upcoming session under Globals → Upcoming events.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "webinars".
 */
export interface Webinar {
  id: number;
  sessionStatus: 'upcoming' | 'recorded';
  title: string;
  /**
   * The page's address: /resources/webinars/…  Leave blank to generate it from the title.
   */
  slug?: string | null;
  /**
   * One or two sentences, shown on the banner and the card.
   */
  description: string;
  /**
   * Managed under Categories. Add one there if the right label does not exist yet.
   */
  category: number | Category;
  /**
   * Bhutan time (BTT). Shown on the banner.
   */
  startsAt: string;
  /**
   * Optional. Used to work out the session's length.
   */
  endsAt?: string | null;
  /**
   * Where it happens — “Zoom”, “Microsoft Teams”, or a physical venue.
   */
  platform?: string | null;
  speakers?:
    | {
        name: string;
        /**
         * Title and organisation, e.g. “Lead Engineer, Bhutan NDI”.
         */
        role?: string | null;
        photo?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * How people sign up. Shown as the banner's button.
   */
  registration?: {
    /**
     * The full address, including https://. With none set, the banner shows the session without a button.
     */
    url?: string | null;
    /**
     * The button text.
     */
    label?: string | null;
    /**
     * Optional. e.g. “Free, places limited to 100.”
     */
    note?: string | null;
  };
  /**
   * Where the recording lives, and how long it runs.
   */
  recording?: {
    /**
     * The full address, including https://.
     */
    url?: string | null;
    /**
     * Shown on the card as “Recording · 48 min”.
     */
    durationMinutes?: number | null;
  };
  /**
   * Shown on the recording card. With none set, the card falls back to the design's gradient and play icon.
   */
  thumbnail?: (number | null) | Media;
  /**
   * Optional. A longer description, agenda or write-up, shown on the session's own page.
   */
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Slides or screenshots from the session.
   */
  gallery?:
    | {
        image: number | Media;
        /**
         * Optional. Printed under the image. Leave blank where the picture speaks for itself.
         */
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Slide decks, transcripts or handouts.
   */
  attachments?:
    | {
        file: number | Media;
        /**
         * The link text, e.g. “Annual report 2026”. Not the file name.
         */
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional. Anything left blank falls back to the page's own content, which is usually the right answer.
   */
  meta?: {
    /**
     * Shown in search results and the browser tab. Around 60 characters. Defaults to the title.
     */
    title?: string | null;
    /**
     * The snippet under the search result. Around 155 characters. Defaults to the description.
     */
    description?: string | null;
    /**
     * Used when the page is shared on social media. 1200×630 works everywhere. Defaults to the featured image.
     */
    image?: (number | null) | Media;
    /**
     * Keeps the page out of Google. The page stays reachable by anyone with the link.
     */
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Research, case studies, reports and blogs.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "insights".
 */
export interface Insight {
  id: number;
  title: string;
  /**
   * The page's address: /resources/insights/…  Leave blank to generate it from the title.
   */
  slug?: string | null;
  /**
   * The abstract: what the publication argues or reports, in two or three sentences.
   */
  description: string;
  /**
   * Managed under Categories. Add one there if the right label does not exist yet.
   */
  category: number | Category;
  /**
   * The form it takes, e.g. Research paper, Case study, Field note.
   */
  kind: string;
  /**
   * The date shown on the page and used for ordering.
   */
  publishedAt: string;
  /**
   * Shown on the card and at the top of the page. 16:9 crops best.
   */
  image?: (number | null) | Media;
  /**
   * The paper or report itself, usually a PDF. Offered as a download at the top of the page.
   */
  document?: (number | null) | Media;
  /**
   * Shown beside the date. Roughly 200 words a minute.
   */
  readingMinutes?: number | null;
  /**
   * People or organisations credited. Left empty, no byline is shown.
   */
  authors?:
    | {
        name: string;
        /**
         * Optional, e.g. “Bhutan NDI” or a partner institution.
         */
        affiliation?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional. Set when the version of record is on a journal or partner site; the page links out to it.
   */
  canonicalUrl?: string | null;
  /**
   * The publication's text, where it is being published here in full.
   */
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Datasets, appendices or supplementary files.
   */
  attachments?:
    | {
        file: number | Media;
        /**
         * The link text, e.g. “Annual report 2026”. Not the file name.
         */
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional. Anything left blank falls back to the page's own content, which is usually the right answer.
   */
  meta?: {
    /**
     * Shown in search results and the browser tab. Around 60 characters. Defaults to the title.
     */
    title?: string | null;
    /**
     * The snippet under the search result. Around 155 characters. Defaults to the abstract.
     */
    description?: string | null;
    /**
     * Used when the page is shared on social media. 1200×630 works everywhere. Defaults to the featured image.
     */
    image?: (number | null) | Media;
    /**
     * Keeps the page out of Google. The page stays reachable by anyone with the link.
     */
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Definitions for the vocabulary of decentralised identity.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "glossary".
 */
export interface Glossary {
  id: number;
  /**
   * The term as it should read, e.g. “Verifiable Credential”. Capitalise it the way the field does.
   */
  term: string;
  /**
   * Leave blank to generate it from the title.
   */
  slug?: string | null;
  /**
   * Plainly, in one or two sentences, without using the term itself to define it.
   */
  definition: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Optional, e.g. “VC”. Searchable alongside the term.
   */
  abbreviation?: string | null;
  /**
   * Optional. Groups terms on the page once there are enough to need grouping.
   */
  category?: (number | null) | Category;
  /**
   * Optional. Other entries a reader of this one should see.
   */
  relatedTerms?: (number | Glossary)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Who appears in the team section of the Company page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members".
 */
export interface TeamMember {
  id: number;
  name: string;
  /**
   * The job title as it should appear, e.g. “Head of Engineering”.
   */
  role: string;
  tier: 'leadership' | 'team';
  /**
   * A portrait, square or taller. With none set, the card shows a monogram — which is the intended fallback, not a placeholder to rush.
   */
  photo?: (number | null) | Media;
  /**
   * Optional. A CSS object-position such as “50% 20%”, to pull the crop up towards the face. Defaults to centre.
   */
  photoPosition?: string | null;
  /**
   * Lower numbers appear first within their tier. Ties fall back to name.
   */
  order: number;
  /**
   * Not shown on the site yet. Recorded for grouping the team page later.
   */
  department?: string | null;
  /**
   * Not shown on the site yet. Kept for a future profile page.
   */
  biography?: string | null;
  /**
   * Not shown on the site. Publishing individual addresses on a public page invites scraping; the footer's shared inbox is the contact route.
   */
  email?: string | null;
  /**
   * Not shown on the site yet.
   */
  socialLinks?:
    | {
        platform: 'linkedin' | 'x' | 'github' | 'website';
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Questions and answers, grouped by who is asking.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  /**
   * As a visitor would ask it, e.g. “What happens if I lose my phone?”
   */
  question: string;
  /**
   * Answer it directly in the first sentence, then explain.
   */
  answer: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Which audience this answer is for. Managed under Categories.
   */
  category: number | Category;
  /**
   * Lower numbers appear first within the category. Put the questions everyone asks at the top.
   */
  order: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * Articles, interviews and features published elsewhere. Each entry links straight out to the outlet.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media-coverage".
 */
export interface MediaCoverage {
  id: number;
  /**
   * The headline as the outlet published it.
   */
  title: string;
  /**
   * Leave blank to generate it from the title.
   */
  slug?: string | null;
  /**
   * Where the card sends the reader — the outlet's own page for this article. Must start with https://.
   */
  url: string;
  /**
   * Who published it, e.g. Kuensel, BBS, The Bhutanese.
   */
  outlet: string;
  /**
   * A short description of what the piece covers, in your own words. Do not paste the article.
   */
  excerpt: string;
  /**
   * Managed under Categories. Add one there if the right label does not exist yet.
   */
  category: number | Category;
  /**
   * The date shown on the page and used for ordering.
   */
  publishedAt: string;
  /**
   * Shown on the card. Use an image the programme owns or is licensed to use — not the outlet's own photography.
   */
  image?: (number | null) | Media;
  /**
   * Extra metadata; not currently shown on the card.
   */
  coverageType?: ('article' | 'interview' | 'broadcast' | 'podcast' | 'report') | null;
  /**
   * The language the piece was published in.
   */
  language?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Vacancies, their terms of reference, and what each one asks applicants to submit.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jobs".
 */
export interface Job {
  id: number;
  title: string;
  /**
   * The page's address: /careers/…  Leave blank to generate it from the title.
   */
  slug?: string | null;
  /**
   * One line on the vacancy card. What the role is responsible for, not what the team does.
   */
  summary: string;
  /**
   * The paragraph under the job title. What the person will own, and how the work is measured.
   */
  about: string;
  /**
   * The body of the notice. Add, rename or reorder these to match the post.
   */
  sections: {
    /**
     * e.g. Duties and responsibilities.
     */
    heading: string;
    /**
     * One statement per point. Full sentences.
     */
    items: {
      text: string;
      id?: string | null;
    }[];
    id?: string | null;
  }[];
  /**
   * e.g. Engineering, Communications.
   */
  department: string;
  /**
   * Seniority, e.g. Senior, Officer, Intern.
   */
  level: string;
  location: string;
  employmentType: 'full-time' | 'part-time' | 'contract';
  /**
   * How many people are being hired.
   */
  slots: number;
  postedAt: string;
  /**
   * The signed notice, offered as a download on the vacancy page. The clauses above are what a candidate reads on screen; this is the document of record.
   */
  torDocument?: (number | null) | Media;
  /**
   * Any other document the notice refers to — a job description, a pay scale.
   */
  attachments?:
    | {
        file: number | Media;
        /**
         * The link text, e.g. “Annual report 2026”. Not the file name.
         */
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * A closed vacancy keeps its page so the notice stays readable, but it is dropped from the careers listing and submissions are refused. Use Closed while you are still drafting a notice.
   */
  recruitmentStatus: 'open' | 'closed';
  /**
   * The last day applications are accepted, inclusive. Enforced on the server — reopening a lapsed vacancy means moving this date, not just switching the status back to open.
   */
  closesAt: string;
  /**
   * An application missing any of these is refused. Ask for what the eligibility clauses actually test — every extra document is a barrier and a data-protection obligation.
   */
  requiredDocuments: (
    'cv' | 'cover-letter' | 'class-10' | 'class-12' | 'higher-education' | 'experience' | 'other-education' | 'other'
  )[];
  /**
   * Offered on the form, but an application without them is accepted.
   */
  optionalDocuments?:
    | (
        | 'cv'
        | 'cover-letter'
        | 'class-10'
        | 'class-12'
        | 'higher-education'
        | 'experience'
        | 'other-education'
        | 'other'
      )[]
    | null;
  /**
   * On, a second application from the same email replaces nothing and is flagged as a duplicate for HR to reconcile — which is usually what someone correcting a mistake needs. Off, the second attempt is refused.
   */
  allowResubmission?: boolean | null;
  /**
   * Optional. Shown above the form, e.g. what to name files, or who to contact about access needs.
   */
  applicationInstructions?: string | null;
  /**
   * Everything submitted for this vacancy, newest first.
   */
  applications?: {
    docs?: (number | JobApplication)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * Optional. Anything left blank falls back to the page's own content, which is usually the right answer.
   */
  meta?: {
    /**
     * Shown in search results and the browser tab. Around 60 characters. Defaults to the title.
     */
    title?: string | null;
    /**
     * The snippet under the search result. Around 155 characters. Defaults to the summary.
     */
    description?: string | null;
    /**
     * Used when the page is shared on social media. 1200×630 works everywhere. Defaults to the featured image.
     */
    image?: (number | null) | Media;
    /**
     * Keeps the page out of Google. The page stays reachable by anyone with the link.
     */
    noIndex?: boolean | null;
  };
  /**
   * Highlight this vacancy at the top of the careers page.
   */
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Everything submitted through the site. Private to HR and superadmin — never visible on the public site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "job-applications".
 */
export interface JobApplication {
  id: number;
  /**
   * Quoted to the applicant. Generated on submission.
   */
  reference: string;
  /**
   * Where this application has got to. Every change is recorded in the timeline.
   */
  status:
    | 'submitted'
    | 'under-review'
    | 'shortlisted'
    | 'interview-scheduled'
    | 'interviewed'
    | 'assessment'
    | 'reference-check'
    | 'selected'
    | 'offer-sent'
    | 'hired'
    | 'rejected'
    | 'withdrawn';
  /**
   * Whose desk this is on. Leave empty for the shared pool.
   */
  assignedTo?: (number | null) | User;
  /**
   * Set on submission and fixed — an application belongs to one vacancy.
   */
  job: number | Job;
  jobTitleSnapshot?: string | null;
  /**
   * Copied from the form so the list and search have something to show.
   */
  applicantName: string;
  applicant: {
    fullName: string;
    email: string;
    /**
     * As given, e.g. +975 17 000 000.
     */
    phone: string;
    /**
     * The 11-digit CID. Collected because Bhutanese citizenship is an eligibility criterion on these posts.
     */
    citizenshipId?: string | null;
    /**
     * Dzongkhag, or the city they are applying from.
     */
    location: string;
    /**
     * Optional. Full postal address, where one was given.
     */
    address?: string | null;
    /**
     * Only collected where a post carries an age criterion. Otherwise left empty.
     */
    dateOfBirth?: string | null;
    /**
     * Where citizenship is a stated criterion.
     */
    nationality?: string | null;
  };
  education?: {
    highestLevel?: ('class-10' | 'class-12' | 'diploma' | 'bachelors' | 'masters' | 'doctorate') | null;
    graduationYear?: number | null;
    /**
     * e.g. BE Computer Science, CST Phuentsholing.
     */
    qualification?: string | null;
    classXPercent?: number | null;
    classXIIPercent?: number | null;
    degreePercent?: number | null;
  };
  experience?: {
    years?: number | null;
    currentEmployer?: string | null;
    /**
     * Whatever link they gave. Not validated — treat with care.
     */
    portfolioUrl?: string | null;
    /**
     * Their own words, as submitted.
     */
    statement?: string | null;
  };
  /**
   * What the applicant attached. Read-only: these are their submission, not a working folder.
   */
  documents?:
    | {
        kind:
          | 'cv'
          | 'cover-letter'
          | 'class-10'
          | 'class-12'
          | 'higher-education'
          | 'experience'
          | 'other-education'
          | 'other';
        document: number | ApplicantDocument;
        id?: string | null;
      }[]
    | null;
  /**
   * Internal. Never shown to the applicant.
   */
  internalDocuments?:
    | {
        document: number | ApplicantDocument;
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional. Recorded against this change in the timeline, then cleared. Use it for the one line that explains the decision.
   */
  statusChangeNote?: string | null;
  /**
   * Every status change, in order. Appended automatically — there is nothing to fill in here.
   */
  statusHistory?:
    | {
        from?: string | null;
        to: string;
        changedAt: string;
        changedBy?: (number | null) | User;
        /**
         * Carried over from the reason given at the time.
         */
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Screening, interview and reference notes. Strictly internal — this collection is unreadable to anyone but HR and superadmin, and no public endpoint returns it.
   */
  internalNotes?:
    | {
        note: string;
        author?: (number | null) | User;
        createdAt?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Filled in once an interview is arranged.
   */
  interview?: {
    scheduledAt?: string | null;
    mode?: ('in-person' | 'video' | 'phone') | null;
    /**
     * Who is interviewing.
     */
    panel?: string | null;
    notes?: string | null;
  };
  assessment?: {
    /**
     * However the panel scores it. No scale is imposed here.
     */
    score?: number | null;
    notes?: string | null;
  };
  referenceCheck?: {
    completed?: boolean | null;
    notes?: string | null;
  };
  /**
   * Why this application did not proceed. Internal — but write it as though the applicant may one day ask.
   */
  rejectionReason?: string | null;
  /**
   * Set automatically when the same email applies to the same vacancy twice. Both records are kept — the later one is usually a correction — and it is for HR to decide which to progress.
   */
  duplicateOf?: (number | null) | JobApplication;
  submittedAt?: string | null;
  consent?: {
    given?: boolean | null;
    at?: string | null;
    /**
     * The wording the applicant agreed to, as it stood that day.
     */
    statement?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Who can sign in to the CMS, and what each of them may do.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Shown on assigned applications and in the audit trail.
   */
  name: string;
  /**
   * Superadmin: everything, including accounts. HR: careers, applications, team, FAQs. PR: newsroom, webinars, publications, glossary, media coverage.
   */
  roles: ('superadmin' | 'hr' | 'pr')[];
  /**
   * Optional. Context for whoever inherits an assigned application.
   */
  jobTitle?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Private. Files attached to job applications, reachable only from the application that owns them.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "applicant-documents".
 */
export interface ApplicantDocument {
  id: number;
  /**
   * Which requirement this file was submitted against.
   */
  kind:
    'cv' | 'cover-letter' | 'class-10' | 'class-12' | 'higher-education' | 'experience' | 'other-education' | 'other';
  originalFilename?: string | null;
  /**
   * What the CMS did to this file when it was uploaded. Set automatically.
   */
  optimization?: {
    strategy?: string | null;
    originalBytes?: number | null;
    optimizedBytes?: number | null;
    note?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {};
}
/**
 * What was done to which application, when, and by whom.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-log".
 */
export interface AuditLog {
  id: number;
  occurredAt: string;
  action:
    | 'application.submitted'
    | 'application.status-changed'
    | 'application.assigned'
    | 'application.note-added'
    | 'application.updated'
    | 'application.deleted'
    | 'job.closed'
    | 'job.reopened';
  summary: string;
  /**
   * Empty where the action was the applicant's own — a submission, say.
   */
  actor?: (number | null) | User;
  collectionSlug: string;
  documentId: string;
  /**
   * Kept here so the entry stays meaningful if the application is removed.
   */
  reference?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'news';
        value: number | News;
      } | null)
    | ({
        relationTo: 'webinars';
        value: number | Webinar;
      } | null)
    | ({
        relationTo: 'insights';
        value: number | Insight;
      } | null)
    | ({
        relationTo: 'glossary';
        value: number | Glossary;
      } | null)
    | ({
        relationTo: 'team-members';
        value: number | TeamMember;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'media-coverage';
        value: number | MediaCoverage;
      } | null)
    | ({
        relationTo: 'jobs';
        value: number | Job;
      } | null)
    | ({
        relationTo: 'job-applications';
        value: number | JobApplication;
      } | null)
    | ({
        relationTo: 'applicant-documents';
        value: number | ApplicantDocument;
      } | null)
    | ({
        relationTo: 'audit-log';
        value: number | AuditLog;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  credit?: T;
  optimization?:
    | T
    | {
        strategy?: T;
        originalBytes?: T;
        optimizedBytes?: T;
        note?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        content?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  taxonomy?: T;
  slug?: T;
  order?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news_select".
 */
export interface NewsSelect<T extends boolean = true> {
  format?: T;
  title?: T;
  headline?: T;
  slug?: T;
  excerpt?: T;
  category?: T;
  publishedAt?: T;
  image?: T;
  body?: T;
  gallery?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  attachments?:
    | T
    | {
        file?: T;
        label?: T;
        id?: T;
      };
  byline?: T;
  externalUrl?: T;
  source?:
    | T
    | {
        url?: T;
        label?: T;
        kind?: T;
      };
  featured?: T;
  popularRank?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "webinars_select".
 */
export interface WebinarsSelect<T extends boolean = true> {
  sessionStatus?: T;
  title?: T;
  slug?: T;
  description?: T;
  category?: T;
  startsAt?: T;
  endsAt?: T;
  platform?: T;
  speakers?:
    | T
    | {
        name?: T;
        role?: T;
        photo?: T;
        id?: T;
      };
  registration?:
    | T
    | {
        url?: T;
        label?: T;
        note?: T;
      };
  recording?:
    | T
    | {
        url?: T;
        durationMinutes?: T;
      };
  thumbnail?: T;
  body?: T;
  gallery?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  attachments?:
    | T
    | {
        file?: T;
        label?: T;
        id?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "insights_select".
 */
export interface InsightsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  category?: T;
  kind?: T;
  publishedAt?: T;
  image?: T;
  document?: T;
  readingMinutes?: T;
  authors?:
    | T
    | {
        name?: T;
        affiliation?: T;
        id?: T;
      };
  canonicalUrl?: T;
  body?: T;
  attachments?:
    | T
    | {
        file?: T;
        label?: T;
        id?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "glossary_select".
 */
export interface GlossarySelect<T extends boolean = true> {
  term?: T;
  slug?: T;
  definition?: T;
  abbreviation?: T;
  category?: T;
  relatedTerms?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members_select".
 */
export interface TeamMembersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  tier?: T;
  photo?: T;
  photoPosition?: T;
  order?: T;
  department?: T;
  biography?: T;
  email?: T;
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  category?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media-coverage_select".
 */
export interface MediaCoverageSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  url?: T;
  outlet?: T;
  excerpt?: T;
  category?: T;
  publishedAt?: T;
  image?: T;
  coverageType?: T;
  language?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jobs_select".
 */
export interface JobsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  summary?: T;
  about?: T;
  sections?:
    | T
    | {
        heading?: T;
        items?:
          | T
          | {
              text?: T;
              id?: T;
            };
        id?: T;
      };
  department?: T;
  level?: T;
  location?: T;
  employmentType?: T;
  slots?: T;
  postedAt?: T;
  torDocument?: T;
  attachments?:
    | T
    | {
        file?: T;
        label?: T;
        id?: T;
      };
  recruitmentStatus?: T;
  closesAt?: T;
  requiredDocuments?: T;
  optionalDocuments?: T;
  allowResubmission?: T;
  applicationInstructions?: T;
  applications?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noIndex?: T;
      };
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "job-applications_select".
 */
export interface JobApplicationsSelect<T extends boolean = true> {
  reference?: T;
  status?: T;
  assignedTo?: T;
  job?: T;
  jobTitleSnapshot?: T;
  applicantName?: T;
  applicant?:
    | T
    | {
        fullName?: T;
        email?: T;
        phone?: T;
        citizenshipId?: T;
        location?: T;
        address?: T;
        dateOfBirth?: T;
        nationality?: T;
      };
  education?:
    | T
    | {
        highestLevel?: T;
        graduationYear?: T;
        qualification?: T;
        classXPercent?: T;
        classXIIPercent?: T;
        degreePercent?: T;
      };
  experience?:
    | T
    | {
        years?: T;
        currentEmployer?: T;
        portfolioUrl?: T;
        statement?: T;
      };
  documents?:
    | T
    | {
        kind?: T;
        document?: T;
        id?: T;
      };
  internalDocuments?:
    | T
    | {
        document?: T;
        label?: T;
        id?: T;
      };
  statusChangeNote?: T;
  statusHistory?:
    | T
    | {
        from?: T;
        to?: T;
        changedAt?: T;
        changedBy?: T;
        note?: T;
        id?: T;
      };
  internalNotes?:
    | T
    | {
        note?: T;
        author?: T;
        createdAt?: T;
        id?: T;
      };
  interview?:
    | T
    | {
        scheduledAt?: T;
        mode?: T;
        panel?: T;
        notes?: T;
      };
  assessment?:
    | T
    | {
        score?: T;
        notes?: T;
      };
  referenceCheck?:
    | T
    | {
        completed?: T;
        notes?: T;
      };
  rejectionReason?: T;
  duplicateOf?: T;
  submittedAt?: T;
  consent?:
    | T
    | {
        given?: T;
        at?: T;
        statement?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "applicant-documents_select".
 */
export interface ApplicantDocumentsSelect<T extends boolean = true> {
  kind?: T;
  originalFilename?: T;
  optimization?:
    | T
    | {
        strategy?: T;
        originalBytes?: T;
        optimizedBytes?: T;
        note?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?: T | {};
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-log_select".
 */
export interface AuditLogSelect<T extends boolean = true> {
  occurredAt?: T;
  action?: T;
  summary?: T;
  actor?: T;
  collectionSlug?: T;
  documentId?: T;
  reference?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  roles?: T;
  jobTitle?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * What the “Upcoming session” card promotes. Leave it empty and the card disappears rather than showing something stale.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "upcoming-events".
 */
export interface UpcomingEvent {
  id: number;
  /**
   * In order. The card shows the first one whose start time has not passed; the design has room for one.
   */
  featured?: (number | Webinar)[] | null;
  /**
   * On, an empty or lapsed selection is filled by the soonest published upcoming webinar — so the card keeps working when nobody remembers to change it. Off, an empty selection means no card.
   */
  fallback?: boolean | null;
  /**
   * Shown in place of the card. Say when to look again, not merely that there is nothing.
   */
  emptyStateNote?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "upcoming-events_select".
 */
export interface UpcomingEventsSelect<T extends boolean = true> {
  featured?: T;
  fallback?: T;
  emptyStateNote?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}